apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: allow-frontend-to-backend
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: frontend-backend-comm
      match:
        resources:
          kinds:
            - Namespace
      generate:
        kind: NetworkPolicy
        apiVersion: networking.k8s.io/v1
        name: allow-frontend-backend
        namespace: "{{request.object.metadata.name}}"
        data:
          spec:
            podSelector:
              matchLabels:
                apptype: backend
            ingress:
              - from:
                  - podSelector:
                      matchLabels:
                        apptype: frontend
            policyTypes:
              - Ingress
