apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: allow-intra-namespace
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: allow-same-namespace
      match:
        resources:
          kinds:
            - Namespace
      generate:
        kind: NetworkPolicy
        apiVersion: networking.k8s.io/v1
        name: allow-intra-namespace
        namespace: "{{request.object.metadata.name}}"
        data:
          spec:
            podSelector: {}
            ingress:
              - from:
                  - podSelector: {}
            egress:
              - to:
                  - podSelector: {}
            policyTypes:
              - Ingress
              - Egress
