apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-default-deny
spec:
  rules:
    - name: add-network-policy
      match:
        resources:
          kinds:
            - Namespace
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - argocd
                - kyverno
      generate:
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        name: default-deny-all
        namespace: '{{request.object.metadata.name}}'
        data:
          spec:
            podSelector: {}
            policyTypes:
              - Ingress
              - Egress
        generateExisting: true