apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-frontend-get-results
  namespace: voting-app
spec:
  endpointSelector:
    matchLabels:
      app: result
  ingress:
    - fromEndpoints:
        - matchLabels:
            apptype: frontend
      toPorts:
        - ports:
            - port: "8081"
              protocol: TCP
          rules:
            http:
              - method: "GET"
                path: "/results"