apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-monitoring-health
  namespace: voting-app
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            role: monitoring
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
          rules:
            http:
              - method: "GET"
                path: "/health"