apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-icmp
  namespace: voting-app
spec:
  endpointSelector: {}
  egress:
  - toEntities:
    - all
    toPorts:
    - ports:
      - protocol: ICMP
  ingress:
  - fromEntities:
    - all
    toPorts:
    - ports:
      - protocol: ICMP