apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubearmor-policies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<your-username>/policy-gitops.git
    targetRevision: HEAD
    path: kubearmor
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
