apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-sensitive-files
  namespace: voting-app # Replace with the specific namespace
spec:
  severity: 5
  message: "Blocking updates to sensitive files"
  selector:
    matchLabels:
      severity: critical # Replace with the appropriate label
  file:
    matchPaths:
      - path: /etc/passwd
        action: Block
      - path: /etc/shadow
        action: Block
      - path: /etc/ssl/private
        action: Block
  process:
    matchPaths:
      - path: /bin/vi
        action: Block
      - path: /bin/nano
        action: Block
  action: Block